/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package jp.gr.java_conf.ka2ush19e.serializations.avro.schema;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Job { 
  Sales, Engineer, Analyst  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Job\",\"namespace\":\"jp.gr.java_conf.ka2ush19e.serializations.avro.schema\",\"symbols\":[\"Sales\",\"Engineer\",\"Analyst\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
